# Generated by Django 5.1.8 on 2025-05-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0001_initial'),
        ('users', '0003_remove_vehicle_school_remove_user_matric_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.student'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip'),
        ),
    ]
