# Generated by Django 5.1.8 on 2025-05-24 02:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0002_school_remove_user_name_user_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matric_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_from', to='trips.route')),
                ('to_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_to', to='trips.route')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='users.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('matric_number', models.CharField(blank=True, max_length=255, unique=True, verbose_name='matric number')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
